import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

import { Roboto } from "next/font/google";

const roboto = Roboto({ weight: ["100", "300", "400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cocina La Antigua",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="blur-nav"></div>
        <nav className="nav">
          <Link className="logo" href="/">
            COCINA LA ANTIGUA
          </Link>
          <ul className={roboto.className}>
            <li>
              <Link href="/">Inicio</Link>
            </li>
            <li>
              <Link href="/menu">Menu</Link>
            </li>
            <li>ES/EN</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
